### ISSUE TITLE
Feature Request. 

### ISSUE THREAD

**Issue by kodilogs** [123Venom/context.venom#1]
Sorry for posting here but couldn’t post it anywhere else on github knowing you would see it. 

I have a feature request for the venom addon.
Just started to use the addon and think its great, especially the download capability.

I was wondering if downloading could be automatic for things from your trakt tv shows collection and movies watchlist. I had an addon that did something similar but its not really working right now.

**Comment by 123Venom** [comment]
Sorry but this does not sound very feasible without allot work.  I'll have to pass on this one.

**Comment by mrXoo** [comment]
Could I just DM you my addon that I was using for you to take a look 😄 or post it here?
