### ISSUE TITLE
Issue with Source Options

### ISSUE THREAD

**Issue by stathis95194** [123Venom/context.venom#3]
Sorry for posting here, but couldn't find where to open a bug issue.
I have tried this on 2 installations and the behaviour is the same. 

If you set under Source Options - Scraper Progress Dialog - Scraper Dialog to Background, when you try to play a video it says Preparing Sources 0% No Stream available and stucks there.
The moment you change the dialog to Foreground all is good in the world :)

**Comment by 123Venom** [comment]
I just got a report of this issue also.  Once tested the background scraping is indeed broken.  I've got it fixed already but want to put it through some tests first.  I'll try to push a fix in the next day.

**Comment by 123Venom** [comment]
Update pushed to fix this.  Let me know how it goes

**Comment by stathis95194** [comment]
Updated and Background is now working as expected.

Thanks a lot for this!!
