### ISSUE TITLE
Auth Revoked on Pi 4 reboot using LibreElec

### ISSUE THREAD

**Issue by XeonNAS** [123Venom/context.venom#4]
See log files dumped at http://paste.kodi.tv/ojavalezug

Does not happen all the time, maybe every second reboot or just randomly, but after reboot, the message Auth Revoked pops up after the Kodi UI is loaded, no interaction with accounts/Venom at all. Quite frustrating. It is in relation to my RD account, the only account I store.

The log dump above was taken immediately after the message was removed by clicking OK. Unfortunately it is not logged using debug, can do so if required.

**Comment by 123Venom** [comment]
Well your log contains no errors from the addon or it's dependencies.  RD's was having maintenance issues and many people were getting their accounts reset in various addon, myself included.

Only possible related issue from your log could be this.  You may want to verify your vpn is not on RD's blakclist.
```ERROR: VPN Mgr : (service.py) VPN monitor service detected VPN connection  is not running when it should be
Beyond that this does not appear to be the fault of this addon from provided data.  You may want to enable debugging in My Accounts addon and see if anything additional is reported.

**Comment by 123Venom** [comment]
Well your log contains no errors from the addon or it's dependencies.  RD's was having maintenance issues and many people were getting their accounts reset in various addon, myself included.

Only possible related issue from your log could be this.  You may want to verify your vpn is not on RD's blakclist.
```ERROR: VPN Mgr : (service.py) VPN monitor service detected VPN connection  is not running when it should be```

Beyond that this does not appear to be the fault of this addon from provided data.  You may want to enable debugging in My Accounts addon and see if anything additional is reported.

**Comment by XeonNAS** [comment]
FUunnily enough this happened this morning and it threw an account error, captured it in logs, http://paste.kodi.tv/dojagufoxi but will turn on debug level to see if anything else can be caught next time.

With the VPN, I have it all enabled etc. and it must not be blacklisted by RD as I can search/play once I reauth, could be the start order of VPN service vs. account service? Any way of reordering these?

**Comment by XeonNAS** [comment]
Closed per my second post.
